#!/bin/bash

if [ "${PATHINFO}" != "yes" ];
then
	echo "Could not find required path information"
	exit 1
fi

echo " + Preparing DNS configuration"

if [ -f ${INFO_SITEROOT}/dns/zone.conf ];
then
        echo "    - Zone configuration found. Will not create."
else
        cat ${ADMINTOOLS_HOME}/template/dns/zone.conf | ${ADMINTOOLS_HOME}/bin/process-template site ${INFO_BASE} ip4 ${INFO_IP4} ip6 ${INFO_IP6} dir ${INFO_SITEROOT} > ${INFO_SITEROOT}/dns/zone.conf
	chown -R ${INFO_USER}:${INFO_USER} ${INFO_SITEROOT}/dns/zone.conf
fi

if [ -f ${INFO_SITEROOT}/dns/records.conf ];
then
        echo "    - DNS records are already in place. Will not override."
else
        cat ${ADMINTOOLS_HOME}/template/dns/records.conf | ${ADMINTOOLS_HOME}/bin/process-template site ${INFO_BASE} ip4 ${INFO_IP4} ip6 ${INFO_IP6} dir ${INFO_SITEROOT} > ${INFO_SITEROOT}/dns/records.conf
	chown -R ${INFO_USER}:${INFO_USER} ${INFO_SITEROOT}/dns/records.conf
fi

# Append record to BIND9 config
proceed=`cat /etc/bind/named.conf.automatic | grep ${INFO_SITEROOT} | wc -l`
if [[ $proceed -lt 1 ]];
then
        echo "include \"${INFO_SITEROOT}/dns/zone.conf\";" >> /etc/bind/named.conf.automatic
fi
unset proceed

echo " + Restarting BIND9 configuration service"

# Restart bind service
service bind9 restart
